<?xml version="1.0" encoding="utf-8"?><Database Name="GameDB" Class="GameDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\GameDB.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="RetroConsole.Properties.Settings" SettingsPropertyName="GameDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PubDevs" Member="PubDevs">
    <Type Name="PubDev">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="PubDev_Game" Member="Games" ThisKey="Id" OtherKey="DeveloperID" Type="Game" />
      <Association Name="PubDev_Game1" Member="Games1" ThisKey="Id" OtherKey="PublisherID" Type="Game" />
    </Type>
  </Table>
  <Table Name="dbo.Genres" Member="Genres">
    <Type Name="Genre">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Genre_Game" Member="Games" ThisKey="Id" OtherKey="GenreID" Type="Game" />
    </Type>
  </Table>
  <Table Name="dbo.Games" Member="Games">
    <Type Name="Game">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="PlatformID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReleaseDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Overview" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="GenreID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PublisherID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeveloperID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Rating" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Banner" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="RomPath" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="Genre_Game" Member="Genre" ThisKey="GenreID" OtherKey="Id" Type="Genre" IsForeignKey="true" />
      <Association Name="PubDev_Game" Member="Developer" ThisKey="DeveloperID" OtherKey="Id" Type="PubDev" IsForeignKey="true" />
      <Association Name="PubDev_Game1" Member="Publisher" ThisKey="PublisherID" OtherKey="Id" Type="PubDev" IsForeignKey="true" />
      <Association Name="Platform_Game" Member="Platform" ThisKey="PlatformID" OtherKey="Id" Type="Platform" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Platforms" Member="Platforms">
    <Type Name="Platform">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Filter" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmulatorPath" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="Platform_Game" Member="Games" ThisKey="Id" OtherKey="PlatformID" Type="Game" />
    </Type>
  </Table>
</Database>